ds-discord test
scc-ukim/ds-discordbot pull request #5
Opened 2022-02-10 06:13 UTC by harfely

[ds-discordbot.zip](https://github.com/scc-ukim/ds-discordbot/files/8038548/ds-discordbot.zip)

2022-02-13 23:41 UTC, EmptyWork requested changes
Masih ada beberapa hal yang harus diubah.

Selain itu file `maju.html` harus di hapus juga.

2022-02-13 23:41 UTC, EmptyWork commented on .vscode/launch.json
> +}
File ini harus karena tasknya untuk C++

2022-02-13 23:41 UTC, EmptyWork commented on .vscode/workspace.code-workspace
> +}
File ini juga harus di hapus, atau tambah `.vscode/` ke `.gitignore`

2022-02-13 23:41 UTC, EmptyWork commented on main.py
> +bot = commands.Bot(command_prefix=">>>")
```suggestion
BOT_PREFIX=">>>"
bot = commands.Bot(command_prefix=BOT_PREFIX)
```

2022-02-13 23:41 UTC, EmptyWork commented on main.py
> +            return
Mungkin bisa tambahkan fitur untuk kelolah isi `message`

Karena pake `discord.ext` bisa ubah ke bentuk fungsi, mengikuti [tutorial ini](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html)

2022-02-13 23:41 UTC, EmptyWork commented on main.py
> +            return
Seharusnya tidak perlu pake tanda `!` diawal teks karena akan di atur pada line 9

2022-02-13 23:41 UTC, EmptyWork commented on main.py
> +
```suggestion
client.run(BOT_TOKEN)
```
Gunakan lib `dotenv` untuk BOT_TOKENnya.

2022-02-14 03:09 UTC, harfely commented
Siap ka glen, beta baru liat soalnya di sini lampu baru manyala kaka,,

Pada tanggal Sen, 14 Feb 2022 pukul 06.41 Stevarth ***@***.***>
menulis:

> ***@***.**** requested changes on this pull request.
>
> Masih ada beberapa hal yang harus diubah.
>
> Selain itu file maju.html harus di hapus juga.
> ------------------------------
>
> In .vscode/launch.json
> <https://github.com/scc-ukim/ds-discordbot/pull/5#discussion_r805432129>:
>
> > +{
>
> +    // Use IntelliSense to learn about possible attributes.
>
> +    // Hover to view descriptions of existing attributes.
>
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>
> +    "version": "0.2.0",
>
> +    "configurations": [
>
> +        {
>
> +            "name": "g++.exe - Build and debug active file",
>
> +            "type": "cppdbg",
>
> +            "request": "launch",
>
> +            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
>
> +            "args": [],
>
> +            "stopAtEntry": false,
>
> +            "cwd": "${fileDirname}",
>
> +            "environment": [],
>
> +            "externalConsole": false,
>
> +            "MIMode": "gdb",
>
> +            "miDebuggerPath": "D:\\G++Install\\mingw32\\bin\\gdb.exe",
>
> +            "setupCommands": [
>
> +                {
>
> +                    "description": "Enable pretty-printing for gdb",
>
> +                    "text": "-enable-pretty-printing",
>
> +                    "ignoreFailures": true
>
> +                }
>
> +            ],
>
> +            "preLaunchTask": "C/C++: g++.exe build active file"
>
> +        }
>
> +    ]
>
> +}
>
>
> File ini harus karena tasknya untuk C++
> ------------------------------
>
> In .vscode/workspace.code-workspace
> <https://github.com/scc-ukim/ds-discordbot/pull/5#discussion_r805432224>:
>
> > +{
>
> +	"folders": [
>
> +		{
>
> +			"path": ".."
>
> +		},
>
> +		{
>
> +			"path": "D:\\XamppInstall\\htdocs\\PortalProject\\Web Jemaat GPM Makariki\\Cosmix Free Website Template - Free-CSS.com\\cosmix"
>
> +		}
>
> +	],
>
> +	"settings": {}
>
> +}
>
>
> File ini juga harus di hapus, atau tambah .vscode/ ke .gitignore
> ------------------------------
>
> In main.py
> <https://github.com/scc-ukim/ds-discordbot/pull/5#discussion_r805432712>:
>
> > +
>
> +bot = commands.Bot(command_prefix=">>>")
>
>
> ⬇️ Suggested change
>
> -
>
> -bot = commands.Bot(command_prefix=">>>")
>
> +BOT_PREFIX=">>>"
>
> +bot = commands.Bot(command_prefix=BOT_PREFIX)
>
>
> ------------------------------
>
> In main.py
> <https://github.com/scc-ukim/ds-discordbot/pull/5#discussion_r805433294>:
>
> > +    if message.channel.name == 'general':
>
> +        if user_message.lower() == 'hello':
>
> +            await message.channel.send(f'Hello {username}!')
>
> +            return
>
> +        elif user_message.lower() == 'yourname':
>
> +            await message.channel.send(f'MY Name is DS-DISCORDBOT#8284,  {username}!')
>
> +            return
>
> +        elif user_message.lower() == 'bye':
>
> +            await message.channel.send(f'see you later {username}!')
>
> +            return
>
> +        elif user_message.lower() == '!random':
>
> +            response = f'This is your random number: {random.randrange(1000000)}'
>
> +            await message.channel.send(response)
>
> +            return
>
> +        if user_message.lower() == '!anywhere':
>
> +            await message.channel.send('This can be used anywhere!')
>
> +            return
>
>
> Mungkin bisa tambahkan fitur untuk kelolah isi message
>
> Karena pake discord.ext bisa ubah ke bentuk fungsi, mengikuti tutorial ini
> <https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html>
> ------------------------------
>
> In main.py
> <https://github.com/scc-ukim/ds-discordbot/pull/5#discussion_r805433295>:
>
> > +        elif user_message.lower() == '!random':
>
> +            response = f'This is your random number: {random.randrange(1000000)}'
>
> +            await message.channel.send(response)
>
> +            return
>
> +        if user_message.lower() == '!anywhere':
>
> +            await message.channel.send('This can be used anywhere!')
>
> +            return
>
>
> Seharusnya tidak perlu pake tanda ! diawal teks karena akan di atur pada
> line 9
> ------------------------------
>
> In main.py
> <https://github.com/scc-ukim/ds-discordbot/pull/5#discussion_r805433507>:
>
> > +client.run('OTM0NDM2NzMwNzcyMjkxNTg0.YewEBQ.Y-mKAQVp63S2wtJdJymPmthJtJw')
>
> +
>
>
> ⬇️ Suggested change
>
> -client.run('OTM0NDM2NzMwNzcyMjkxNTg0.YewEBQ.Y-mKAQVp63S2wtJdJymPmthJtJw')
>
> -
>
> +client.run(BOT_TOKEN)
>
>
> Gunakan lib dotenv untuk BOT_TOKENnya.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scc-ukim/ds-discordbot/pull/5#pullrequestreview-881060062>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUK5743Q3EU47X4I43SQ6KLU3A6T5ANCNFSM5N7V7LDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2026-05-01 02:54 UTC, closed without merging